### DISCUSSION TITLE
Edit single instance of recurring event

### DISCUSSION THREAD

**Discussion by ascsanto** [davish/obsidian-full-calendar#365] [Feature Requests]
I don't know if i should put this on bug report or feature request.
Let's say i have a 2h long task recurrent every day, and let's say that i'm planning my next day and i don't have time to do this task, i would need the possibility to remove only that single istance of the recurrent task. What happens is that i can only remove all of them.
A similar thing happens if i just want to modify a single istance, if i want to resize it (e.g. from 2h to 1h) or if i want to postpone the task only for a single day istance, what happens is that the event becomes a single time event and all the other recurrences disappear, and this is kinda annoying for my usecase.

**Comment by ascsanto** [comment]
I don't know how this could be fixed, but even automatically creating a new single event with a note that has a link to the main (recurrent) note would be better then removing all the recurrences in the calendar, in my opinion

**Comment by safrilth** [comment]
I have a thought that this issue #90 is related to issue number #21 . But I don't really understand whether this approach is efficient & performant or not, from a technical point of view, because I'm not a programmer. I will explain it with several scenarios, to make it easier to explain.

*English is not my native language, I use google translate to communicate. I hope my conversation here is understandable* 😊 

## Setup
- Current Date : 17-05-2022
- Goal: Make a Recurring Date every Monday for 1 Month (May 2022)

## Scenario 1, Creating a Recurring Event
The event is created using the existing `modals form` as usual, and will return a Yaml like this :

```yaml
# basic event yaml
title: task
allDay: false
startTime: [18:30, 18:30, 18:30, 18:30, 18:30]
endTime: [20:30, 20:30, 20:30, 20:30, 20:30]
date: [2022-05-02, 2022-05-09, 2022-05-16, 2022-05-23, 2022-05-30 ]
# recurring rule (optional if user choose recurring option)
type: recurring
daysOfWeek: [M]
startRecur: 2022-05-01
endRecur: 2022-05-31
```

`Recurring Rule` is meant to generate data on `basic event yaml` (`startTime, endTime, date`) , so that each instance can be edited manually

## Scenario 1.1, Manual Time Rescheduling
Time Changed manually (by drag n drop) on `Calendar View` :
- First Monday to 09:00 - 10:00
- Fourth Monday to 11:00 - 12:00
Then it will generate Yaml :

```yaml
title: task
allDay: false
startTime: [09:00, 18:30, 18:30, 11:00, 18:30]
endTime: [10:00, 20:30, 20:30, 12:00, 20:30]
date: [2022-05-02, 2022-05-09, 2022-05-16, 2022-05-23, 2022-05-30 ]
# recurring rule (optional if user choose recurring option)
type: recurring
daysOfWeek: [M]
startRecur: 2022-05-01
endRecur: 2022-05-31
```

## Scenario 1.2, Batch Rescheduling
Batch Rescheduling is a command to edit `startTime, endTime, or date` .

UX :
- the initial development can be in the form of a command palette
- the future development can be right click on an event in `Calendar View`

Some Examples of Batch Rescheduling Command :
- Edit Time
	- for Past Event : it will change `startTime & endTime` on `date before 2022-05-17` 
	- for Future Event : it will change `startTime & endTime` on  `date after 2022-05-17`
	- for Selected Range : it will change `startTime & endTime` on spesific range within `startRecur & endRecur`
- Edit Date : is it possible ? see scenario 1.3 first
	- for Past Event
	- for Future Event
	- For Selected Range

## Scenario 1.3, Manual Date Rescheduling
Date changed manually (by drag n drop) on `Calendar View` :
- First Monday (2022-05-02) shifted to Tuesday (2022-05-03)

Will produce 2 results (I honestly don't know which is the best approach)
1. It will fail : Because violating the `recurring rule`
2. It will continue to run normally, even if it violates the `recurring rule`

The solution I offer, is to add one more mode, namely `strict recurring` . If `strict recurring` is `true` then the user cannot change the date of an event.

An example of the yaml generated on `non strict recurring` is as follows:

```yaml
title: task
allDay: false
startTime: [18:30, 18:30, 18:30, 11:00, 18:30]
endTime: [20:30, 20:30, 20:30, 12:00, 20:30]
date: [2022-05-03, 2022-05-09, 2022-05-16, 2022-05-23, 2022-05-30 ]
# recurring rule (optional if user choose recurring option)
type: recurring
daysOfWeek: [M] # this line will be less meaningful, maybe it should be deleted
startRecur: 2022-05-01
endRecur: 2022-05-31
```

The tradeoff of `non strict recurring` is that the `daysOfWeek` line will become less meaningful.

An example of the resulting yaml `strict recurring`, which cannot change the date (only change the time), as follows :

```yaml
title: task
allDay: false
startTime: [13:00, 18:30, 18:30, 11:00, 18:30]
endTime: [14:00, 20:30, 20:30, 12:00, 20:30]
date: [2022-05-02, 2022-05-09, 2022-05-16, 2022-05-23, 2022-05-30 ]
# recurring rule (optional if user choose recurring option)
type: strict recurring
daysOfWeek: [M] # in strict mode, this line has meaning again
startRecur: 2022-05-01
endRecur: 2022-05-31
```

further survey is needed to determine what default value is suitable for `strict recurring`. But I think a suitable default value is `false`, because `strict recurring` itself is less intuitive, and is probably the least expected behavior.


## Scenario 2, Multiple Scheduling 
The issue (#21) is actually talking about `Multiple Scheduling` , then how is it different from the `Recurring` feature? So, What is the fundamental difference? here are my thoughts on both things

| Condition      | Multiple Scheduling                                                                                                                  | Recurring Rule                                                       |
| -------------- | ------------------------------------------------------------------------------------------------------------------------------------ | -------------------------------------------------------------------- |
| initial creation | generate one value of `scheduling` `(startTime, endTime, date)`                                                                      | generate multiple value of `scheduling` `(startTime, endTime, date)` |
| event editing  | enter `scheduling` values one by one. Initial UX by writing yaml one by one, the final UX can be a right click of an event in the `calendar view` |  reschedule manually (drag n drop or yaml) / batch rescheduling                                      |
| yuml structure | just `basic event yaml`                                                                                                             | `basic event yaml + recurring rule`                                  |
| rescheduling rules   | not bound by rules, just drag n drop                                                                                           | can choose to be bound by rules (`strict recurring`) or not         |

## Conclution
I am a big fan of this plugin, so I try to give good feedback by connecting the dots between issues that arise on github. Hopefuly this idea will usefull for future development. 😊
