### ISSUE TITLE
Tooltip to visualize the description the events

### ISSUE THREAD

**Issue by FabianoLothor** [davish/obsidian-full-calendar#262]
Currently the week-view doesn't show the description of events pretty well, specially when there are multiple events at the same time, or when the event is too short (let's say, 30 minutes).

My suggestion here is to add a tooltip when hovering an event.

Look:

![image](https://user-images.githubusercontent.com/2192995/215302840-042b2aa1-6e78-4123-8900-efa9af40b0b0.png)

It's super messy.

---

What I did temporarily was create a CSS snippet to fix this behavior to me.

```css
/**
 * Array.from(document.querySelectorAll(".fc-event-main-frame")).forEach(element => element.addEventListener('click', function() { alert(Array.from(element.children).map(children => children.textContent).join(', ')) }))
*/

.fc-timeGridWeek-view .fc-timegrid-event-harness:hover {
    left: 5% !important;
    width: 90%;
    height: 100px;

    z-index: 999 !important;
}

.fc-timeGridWeek-view .fc-timegrid-event-harness:hover .fc-timegrid-event-short .fc-event-main-frame {
    flex-direction: column;
    overflow: inherit;
}

.fc-timeGridWeek-view .fc-timegrid-event-harness:hover .fc-timegrid-event-short .fc-event-time:after {
    content: none;
}
```

The result when hovering an event, will be something like that:

![image](https://user-images.githubusercontent.com/2192995/215302934-a689f87f-8f7a-4857-b45a-dccc25c4de96.png)

The daily view works fine for my needs, but if you want/need this behavior there too, just remove the class `.fc-timeGridWeek-view`
