### ISSUE TITLE
Calendar in sidebar

### ISSUE THREAD

**Issue by blackpeasy** [davish/obsidian-full-calendar#51]
I love the idea of having the calendar in day view in the sidebar as a daily agenda. 

However, the calendar looks rather bulky when sized down to that size. Is it possible to make it integrate better into the sidebar?

<img width="733" alt="image" src="https://user-images.githubusercontent.com/92858268/157633823-58ad8270-3143-47cd-9d54-52afd429b152.png">

**Comment by MajorEnkidu** [comment]
The following CSS rules could fix that issue at least for the toolbar:

```css
.fc .fc-toolbar {
	flex-wrap: wrap;
    margin-top: -0.375em;
    margin-bottom: -0.375em;
}

.fc .fc-toolbar-chunk {
	margin-top: 0.375em;
    margin-bottom: 0.375em;
}
```
Worst case:
![image](https://user-images.githubusercontent.com/97227530/164892751-05f92d97-49b5-40c4-9b51-c183743638fa.png)

Smallest normal toolbar:
![image](https://user-images.githubusercontent.com/97227530/164892775-34b7b4c5-5d42-4eac-8659-b658f894fe74.png)

Medium sized toolbar:
![image](https://user-images.githubusercontent.com/97227530/164892898-3d8aebf4-e51d-4dd6-bd03-2cb223b28dcb.png)
