### ISSUE TITLE
Calendar Doesn't Display when frontmatter values are malformed in a single event

### ISSUE THREAD

**Issue by ktmeaton** [davish/obsidian-full-calendar#61]
**Describe the bug**
The calendar won't display if certain values are specified for `startTime`/`endTime` in the yaml frontmatter.

**Steps to reproduce**
Ex. Calendar displays correctly:

```yaml
date: 2022-03-14
startTime: 09:00
endTime: 10:00
```

Ex. Calendar doesn't display at all (blank):

```yaml
date: 2022-03-14
startTime: "--"
endTime: "--
```

Previously, I've used `startTime: "--"` as a placeholder for events I hadn't scheduled yet in other Obsidian plugins. I don't think this is actually a "bug" that needs to be fixed.  I just wanted to document it in case anyone else had the same issue.

Thanks for such an excellent calendar plugin!
